# Generated by Django 4.2 on 2023-04-26 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollowing",
            old_name="following_user_id",
            new_name="follower_id",
        ),
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together={("user_id", "follower_id")},
        ),
    ]
